### ISSUE TITLE
Misleading name. Propose rename `NewOutputs` -> `NewSortedOutputs`

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/goshimmer#1040]
https://github.com/iotaledger/goshimmer/blob/dd0f22f6920dc845eb01501b71cb11647d848cab/packages/ledgerstate/output.go#L278
The `type Outputs []Output` does not enforce sorting itself. However `NewOuputs(inputs)` return resorted elements which makes 
situation nondeterministic, because `Outputs` contain same element but in a different (random) order. 
This is misleading, for example in https://github.com/iotaledger/goshimmer/blob/dd0f22f6920dc845eb01501b71cb11647d848cab/packages/ledgerstate/utils.go#L53 where index should be as we assigned it in the list.  
`NewSortedOutputs(inputs)` would be a better name

**Comment by hmoog** [comment]
The Outputs will not be parsable if they are not sorted because the sorting is part of the syntactical validation phase. I don't think it makes sense to call it NewSortedOutputs because it should not be possible to create invalid outputs through the normal API.

If you want to create an Outputs Object that is not sorted then you can just do

`myUnsortedOutputs := []Output{output1, output2, output2}`

but you need to be aware that every node will reject these outputs.

**Comment by lunfardo314** [comment]
I am referring for example to: https://github.com/iotaledger/goshimmer/blob/51bac590a1ede988ecad3a24d618990005820455/packages/ledgerstate/utils.go#L53
Where `Outputs` is type of the argument. It suggest to use `NewOutputs()` in the call as if we need inputs sorted by output binary representation, which is not true. So, maybe to replace it with `[]Output`  as a type of arguments and rename type `Outputs` to `SortedOutputs` to avoid misunderstanding?
