### ISSUE TITLE
Transaction spammer

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#1127]
We should have a tool to spam transactions from multiple (CLI) wallets easily. It would be good to combine this with 

- valid transactions only
- mix with double spends
- mix with data messages

**Comment by JanOonk** [comment]
Well I am working on a spammer written in .NET Core, it's a wrapper around the commandline cli-wallet which is not ideal. I would rather have used an API. Also I have a fulltime job... so don't bet on it :)
Also the current cli-wallet can't handle multiple parallel transactions gracefully which is slowing down my progress quite a bit and makes my spammer a simple synchronise/sequential spammer instead of parallel spamming capabilities. See issue #1157

But when more people are working on multiple different spammers is always good to have :)
