### ISSUE TITLE
Synced node gets unsynced and gives error: building past consensus base mana vector: %vbase mana should never be negative

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/goshimmer#1184]
## Bug description

I created a new node which got synced fairly quick... but not long there after got unsynced with this error:
`ERROR Mana messagelayer/mana_plugin.go:686 error building past consensus base mana vector: %vbase mana should never be negative`

Btw: the database folder contained 20 items and was 1.75GB in size which seems high(?) for just one day uptime.

## GoShimmer version

v0.5.6

## Hardware specification

Docker on Synology NAS DSM 6

## Steps To reproduce the bug

In my case I just created a new node after deleting the db folder.
It's reproducable. Tried it three times. Same error. See second log which includes the first.
By the way the third time my node did stay in sync for ~6 hours while giving the mana errors before finally getting unsynced.

## Expected behaviour

A synced node without any errors in log

## Actual behaviour

Most of the time an unsynced node

## Errors

`ERROR Mana messagelayer/mana_plugin.go:686 error building past consensus base mana vector: %vbase mana should never be negative`

Full log attached.

[goshimmer-1.html.txt](https://github.com/iotaledger/goshimmer/files/6276453/goshimmer-1.html.txt)

[goshimmer-2.html.txt](https://github.com/iotaledger/goshimmer/files/6277244/goshimmer-2.html.txt)

**Comment by Phyloiota** [comment]
Same issue here. My node was long and stable running since beginning of the current version. Was ranked 8-10 in Access and consensus Mana.
From time to time the node received this warning:
[hijacked error.txt](https://github.com/iotaledger/goshimmer/files/6283300/hijacked.error.txt)
this was the first time the error occured.
But got back in sync it seems here:
[back sync after hijack.txt](https://github.com/iotaledger/goshimmer/files/6283304/back.sync.after.hijack.txt)

and then later the above described Mana Error occured:
[mana error1.txt](https://github.com/iotaledger/goshimmer/files/6283306/mana.error1.txt)

Finally is not able to get back ins sync and loops in this error mode:
[Uploading unsynced loop hijacked&mana error.txt…]()
