### ISSUE TITLE
Node is synced but zero current tips, graceful shutdown fails

### ISSUE THREAD

**Issue by luca-yvr** [iotaledger/goshimmer#1418]
## Bug description

on the dashboard, the current tips chart show zero tips, no TXs are possible.  Shutdown fails after countdown, and database is corrupted

## GoShimmer version

Version 0.7.0-2b57453f, but the had the same issue with 0.7.0 release (the same problem occurred twice so far)

## Hardware specification

- Operating system: ubuntu 20.04 LTS
- RAM:  16GB
- Number of cores: 6 cores
- Device type: ESXi VM

## Steps To reproduce the bug

1.  wait for node to show zero tips on current tips chart. All TXs fail with "ERROR:
  bad request: Failed to issue transaction TransactionID(.........): tips could not be selected: not able to make sure that all inputs are in the past cone of selected tips"
2. attempt to shutdown the node (ctrl-c)
3. graceful shutdown fails after countdown runs out, the database is corrupted

## Errors

<img width="787" alt="no tips -gui" src="https://user-images.githubusercontent.com/10619487/121086970-b032ae80-c798-11eb-90ba-3fe2ab022c6a.png">
<img width="799" alt="no tips -neighbors" src="https://user-images.githubusercontent.com/10619487/121086991-b6288f80-c798-11eb-92fa-06e955e9b641.png">
<img width="798" alt="no tips -mana" src="https://user-images.githubusercontent.com/10619487/121087008-bb85da00-c798-11eb-8f73-8ba9541a439f.png">
[no tips - full stack dump before shutdown.txt](https://github.com/iotaledger/goshimmer/files/6611988/no.tips.-.full.stack.dump.before.shutdown.txt)
[no tips - console after shutdown fails.txt](https://github.com/iotaledger/goshimmer/files/6611992/no.tips.-.console.after.shutdown.fails.txt)

**Comment by luca-yvr** [comment]
[logs.zip](https://github.com/iotaledger/goshimmer/files/6612073/logs.zip)

**Comment by jonastheis** [comment]
Looking at the logs does not really reveal anything suspicious. That the node can't select tips that contain your funds in the past cone is obvious, since it has 0 tips and thus the tip selector will return the empty message ID (= genesis message) which does not contain your funds. But that is just a symptom of the overall issue.

The log times are around `2021-06-07T13:32:43-07:00` but the TangleTime is stuck at `11:17:49` but it still thinks it is synced. Am I interpreting this correct, @luca-yvr? If so, this could be a hint on what's going on.

Also, in the stack dump after the shutdown failed there's a bunch of threads waiting in gossip.
```
goroutine 7408 [select, 93 minutes]:
github.com/iotaledger/goshimmer/packages/gossip.(*Neighbor).writeLoop(0xc005e10070)
        /opt/goshimmer/packages/gossip/neighbor.go:115 +0xe7
created by github.com/iotaledger/goshimmer/packages/gossip.(*Neighbor).Listen
        /opt/goshimmer/packages/gossip/neighbor.go:83 +0x87
```
Though in the logs `2021-06-07T13:32:42-07:00	INFO	Gossip	gossip/gossip.go:84	Stopping Gossip ... done` indicates that gossip is shut down. @georgysavva could you take a look at this if that might be the case for the shutdown issue?

**Comment by georgysavva** [comment]
Okay, I will take a look!

**Comment by luca-yvr** [comment]
yes, I noticed the tangleTime being behind actual time after posting this...  With gossip shutdown should I still be seeing 8 neighbors on the neighbor tab?

**Comment by georgysavva** [comment]
@jonastheis @luca-yvr I found the problem with gossip goroutines and fixed it in https://github.com/iotaledger/goshimmer/pull/1426, but I don't think it's related to the main problem of this issue.

**Comment by luca-yvr** [comment]
this happened again (zero current zips, beacon is stuck).  anything i should try before restarting?
<img width="890" alt="no current tips - 3" src="https://user-images.githubusercontent.com/10619487/123888311-129a4d00-d908-11eb-8350-ff5d0bf4b40c.png">
