### ISSUE TITLE
Writer de/serializer for structures

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1593]
Replace the `marshalUtil` with a serializer which takes care of parsing data so we no longer repeat serialization code all over the place and make the code neater.

See iota.go for a sample implementation: https://github.com/iotaledger/iota.go/blob/main/serializer.go then enhance it for more structures present in Coordicide's data models and add it to hive.go.
Bonus: adjust `iota.go` to also use the new serializer in hive.go.

**Comment by piotrm50** [comment]
Added serialization code in `hive.go` repo (https://github.com/iotaledger/hive.go/pull/281).
Extracted the code from `iota.go` and adjusted the code to use `hive.go` (https://github.com/iotaledger/iota.go/pull/290).
Implemented the Serializable interface in Goshimmer (without JSON marshalling) for `Output` type and its field types. (https://github.com/iotaledger/goshimmer/commit/bc3d0bd851e5c81cb3a6f23129d0d34e68a539ec).

`Serialize` and `Deserialize` methods look very similar to existing `Bytes` methods, so it should be discussed whether we should replace MarshalUtil with Serializator as the process is tedious and error-prone.

The code that uses Serializer/Deserializer is longer than its MarshalUtil counterparts, but offers easier error handling and easier handling of objects and slices. However slices of serializables cannot be handled using mechanisms built in the serializer, because of how types are handled in Goshimmer, so we can't use `WriteSliceOfObjects` or `ReadSliceOfObjects` without refactoring the types in Goshimmer, because they are not compatibile.

**Comment by luca-moser** [comment]
Superseded by #1629
