### ISSUE TITLE
Visualizer: Design different scenarios for testing and collect bugs

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#1835]
Design complicated scenarios to test if all DAGs are showing things properly.

list of scenarios:
* [x] simple transaction spam
* [x] double spend
* [x] conflicting branches A-B-C-D-A - first layer

list of bugs:
 - Can not create edge `7bdb8a8c-f82a-4d52-9a9a-7b57b3033301` with unspecified source. Goshimmer panics.
 - dashboard visualizer is broken
 - explorer link broken
 - DAGs visualizer freeze with too many tx spammed, because graph is to long

**Comment by daria305** [comment]
During spam with 10 transactions with 5mps
Error: Can not create edge `7bdb8a8c-f82a-4d52-9a9a-7b57b3033301` with unspecified source
line: `src/iotaledger/goshimmer/plugins/dagsvisualizer/frontend/src/stores/UTXOStore.tsx:262`
Afterwards needs to refreash the page. But the UTXO DAG is loading with no edges. Then crashes entirely
Error is due to loss connection to the goshimmer (nodes paniced in the dashboard package).

Problem on goshimmer side: `panic: interface conversion: ledgerstate.Branch is *ledgerstate.AggregatedBranch, not *ledgerstate.ConflictBranch`

**Comment by daria305** [comment]
Visualizer dashboard does not work properly, all nodes are Unknown and unconnected on the Vizualizer, but docker network and DAGs Visualizer seems to work without any problems

**Comment by daria305** [comment]
Running value spammer for a little longer will freeze the DAGs Visualizer due to UTXO DAG being to long, if it will not crash before due to ' Can not create edge' problem
Need to limit showed outputs
To replicate try with standardized test command:
```
go run main.go quick --urls http://localhost:8080,http://localhost:8090 --rate 50 --duration 1m --tu 1s --dbc 100ms
```

**Comment by jkrvivian** [comment]
@daria305 thanks for testing these! :heart:
