### ISSUE TITLE
Mark messages ready

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/goshimmer#1841]
Enqueue messages to buffer (Scheduler.Submit(id)) after booking.
Mark messages ready (Scheduler.Ready(id)), when their parents are scheduled or confirmed.

**Comment by capossele** [comment]
To ensure that the correct order of messages is accordingly processed by the scheduler we want to mark a message ready to be scheduled according to the following definitions:

A message being submitted to the scheduler is defined **ready** if its timestamp is not in the future and all of its parents are eligible.

A message is defined **eligible** if it has been scheduled or it has been confirmed.

I see 2 different ways of implementing this:

* **lazy**: Within the scheduler main loop we keep popping elements from the selected node's queue and schedule the first element that is *ready*. We can mark it as ready if the above conditions are true. This implies that for each element of the queue we check we need to:
    * look at its timestamp -> not a problem
    * iterate over all of its parents (worst case), load them from the object storage and check if they are eligible -> can be a burden since the main loop of the scheduler should stay as quick as possible to be able to work at fast rates.
* **active**: A separate goroutine (wrt the scheduler) could attach to both the events MessageScheduled and MessageConfirmed and iterate over all its direct approvers and mark them **ready** accordingly. This would allow the scheduler main loop to only read a flag instead of performing directly this operation.
    * A potential problem is that a new message could directly reference a message that has been already scheduled (or confirmed) thus missing its opportunity to be set as *ready*. To solve this we could duplicate this check also in the Setup of the scheduler that currently attaches to the MessageProcessed event (the event triggered by the ApprovalWeight manager).

What do you guys think? Am I overlooking at something? 
@Wollac @piotrm50 @GalRogozinski

**Comment by GalRogozinski** [comment]
@capossele 
Loading from object storage could be an I/O operation (unless it is in cache IIUC), and thus very heavy.
If the *active* can reduce the number of accesses to object storage I would go with it, even at the expense of another go routine.

**Comment by Wollac** [comment]
@capossele @piotrm50 
the scheduler already checks for the correct timestamp:
https://github.com/iotaledger/goshimmer/blob/323f6bbddf77fa1c4c07c2e92adf5857441f755b/packages/tangle/scheduler.go#L305
Back in the days, this was added since in the scheduler it is just this simple check and outside it would probably be uglier with timed callbacks or something.
For the eligibility, I guess I would do the following:
- For every message that gets submitted to the scheduler create a reverse-map to its not yet scheduled (according to the corresponding flag) parents
- Listen to MessageScheduled and remove the corresponding msg from its children wrt to that map. Once a child has no more dependencies mark it as ready.
