### ISSUE TITLE
Resolve NAT problems within autopeering

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#188]
* Split port and address
* Evaluate whether we should automatically get the external IP

**Comment by Wollac** [comment]
*Current verification process*

![verification](https://user-images.githubusercontent.com/4930426/74144186-91e88d00-4bfc-11ea-9954-ee461508db2a.png)

**Considerations:**
- Ping:
  - Does From need to match the the source IP and Port? Only IP? None of them?
  - Send Pong to source address instead of From?
  - Does To need to match own public address?
- Pong:
  - Expected address of Pong? Source or should we introduce From?
  - Is To needed?
