### ISSUE TITLE
Allow interactive mode preventing network shutdown

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#2021]
On debug mode, a user should hit a key when the test ends in order to initiate network shutdown.

**Comment by GalRogozinski** [comment]
In #2069 debug mode enabled on the the test code that is run by the `tester` container.
So now every dev can have this feature for free by adding a breakpoint on the `ShutdownNetwork` function in `testutils.go` (and never delete it).

Since this approach is easy and requires no code, it is the best solution. Especially when considering that `go test` sets `stdin` as `\dev\null`, making all other solutions too hacky to my taste.
