### ISSUE TITLE
Dashboard (potentially) misleading URL in Logs (0.0.0.0)

### ISSUE THREAD

**Issue by bernardoaraujor** [iotaledger/goshimmer#392]
## Bug description

Log info displays (potentially) misleading message about Dashboard's URL.

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: v0.1.3

## Hardware specification

What hardware are you using?

- Device type: Raspberry Pi
- Operating System: honeycombOS

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Run honeycombOS v0.3.0 on a Raspberry Pi 3 or 4.
2. Enable dashboard.
3. Start GoShimmer.
4. Watch logs.

## Expected behaviour

It would make sense that the log that informs the user about the Dashboard being available displayed a generic indication to the Machine's IP. Something like:
```
2020-04-29T21:51:37Z INFO SPA spa/plugin.go:96 You can now access the dashboard using: http://<node_ip_addr>:8081
```

## Actual behaviour

The logs say that Dashboard is available at `http://0.0.0.0:8081`, which is misleading to any user that's expecting to access the Dashboard from a machine that's not the same one running the node.

```
2020-04-29T21:51:37Z INFO SPA spa/plugin.go:96 You can now access the dashboard using: http://0.0.0.0:8081
```
## Errors

Just try to access `http://0.0.0.0:8081` from any machine where there's no node running locally. The browser will not be able to load any page.

**Comment by luca-moser** [comment]
We'll actually change it to simply tell in the log the bind address the plugin uses, instead of guessing where the user could potentially access the dashboard from (or whatever else). This, because we can't really know what configuration the user is running with proxies etc., so even if we would somehow manage to get for example the WAN address, we wouldn't really know if what we're advertising is correct.
