### ISSUE TITLE
Make autopeering filter and ignore offline nodes.

### ISSUE THREAD

**Issue by hmoog** [iotaledger/goshimmer#44]
Nodes that have been offline for a prolonged times should not be contacted by the autopeering forever and ever.

For this, we need to keep track of when a peer was seen the first and the last time and then adjust the filter functions to check these properties.

**Comment by PatriQ94** [comment]
Perhaps we could also extend this so that the autopeering checks open ports, both from neighbors and own ports (and in this case returns appropriate response)? 

Currently there's a lot of issues regarding ports within the community, since non IT people that try to run GoShimmer don't realize that they have to open the ports, once they try to do so they have no way to check if they changed settings correctly, if the ports are open correctly and/or if GoShimmer is running as it should. In general, port checking and appropriate feedback to the users should be required.
