### ISSUE TITLE
The sendTransaction endpoint should use a proper JSON object not serialized binary

### ISSUE THREAD

**Issue by obany** [iotaledger/goshimmer#637]
## Description

The `sendTransaction` endpoint currently has a payload of `txn_bytes: base64 string` which is a serialized version of the data, this is not very RESTful.

## Motivation

The endpoint should receive a standard JSON payload.

## Requirements

The JSON payload should contain the same contents as the serialized binary

e.g.
```js
{
   "inputs": string[],
   "outputs": {
      "id": string,
      "balances": {
          "value": number,
          "color": string
      }[];
    }[],
    "data": string,
    "signatures": {
       "version": number,
       "publicKey": string,
       "signature": string
      }[]
}
```

**Comment by lunfardo314** [comment]
We have to make it sure the binary result will be deterministic, transaction hash should be the same no matter what you do with json. That is the problem I encountered and the preferred binary blob.

**Comment by obany** [comment]
But the structure of the JSON is irrelevant, it is the data contained within that is processed, why is that not deterministic ?

**Comment by lunfardo314** [comment]
The order of the binary data matters. It may be the same content of the json dictionary for example but unmarshalling can result in differently “ordered” maps in Go and I believe in other environments too (different order of iteration). So, your binary object may have different hashes on sender and on receiver side. Sorting in binary is a way to make it deterministic. In goshimmer outputs of value transactions are sorted however inputs are appended as given. That may lead to very subtle bugs due to this kind of nondeterminism, specifically in smart contracts

**Comment by obany** [comment]
But this is just about serializing/deserializing JSON in the API endpoint.

In the example I gave there are no maps just ordered arrays. Assuming the signatures were generated from the essence ordered in the same way it would be deterministic. Even the current binary payload is still open to problems with map ordering as it depends how the iterator in a given language walks the items in the collection to generate the payload.

**Comment by lunfardo314** [comment]
yeah, if the lists are generated deterministically from any equivalent json then it must be ok. Just sharing my experience :)
