### ISSUE TITLE
Dashboard is empty, shows no content 

### ISSUE THREAD

**Issue by Ohios089** [iotaledger/goshimmer#651]
## Bug description

There is no content displayed in the dashboard, but node is running and the connection to the dashboard is there.

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: v0.2.1

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 20.04; Browser Safari 13.1.2
- RAM: 4 GB
- Number of cores: 4
- Device type: Raspberry Pi 4b

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Running the GoShimmer node on the device upon.
2. Make a connection to the dashboard in config.json.
3. Connect to the dashboard in the browser.

## Expected behaviour

Normal data submission on dashboard like in the versions before.

## Actual behaviour

There is no content displayed in the dashboard, but node is running and the connection to the dashboard is there.
<img width="980" alt="Bildschirmfoto 2020-07-18 um 20 25 05" src="https://user-images.githubusercontent.com/60474745/87870085-1823af00-c9a5-11ea-8d7d-89dd670b1fb9.png">

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

**Comment by jonastheis** [comment]
This sounds like a deadlock and is probably the same issue that is documented in #648. It should be fixed with #650. To make sure we'd need some more information. 

Are you running the node with the `profiling` plugin enabled? If yes could you paste the goroutine logs from `pprof`? Default port/address is `http://your_node_ip:6061/debug/pprof/goroutine?debug=1` and `http://your_node_ip:6061/debug/pprof/goroutine?debug=2`

**Comment by Ohios089** [comment]
Hi Jonas. No, I got no plug-in enabled.

**Comment by Ohios089** [comment]
But thanks for mentioning that it will be fixed with #650

**Comment by capossele** [comment]
Fixed by #650
